# SPDX-License-Identifier: GPL-2.0
#
# Make file to build device tree binaries for boards based on
DTC_FLAGS += -@

dtb-$(CONFIG_ARCH_K3) += myd-am62x-6254.dtb
dtb-$(CONFIG_ARCH_K3) += myd-am62x-lvds-j5.dtbo
dtb-$(CONFIG_ARCH_K3) += myd-am62x-lvds-j6.dtbo
dtb-$(CONFIG_ARCH_K3) += myd-am62x-dual-lvds.dtbo
