# SPDX-License-Identifier: GPL-2.0
#
# Make file to build device tree binaries for boards based on
DTC_FLAGS += -@

dtb-$(CONFIG_ARCH_K3) += myd-y62x-6254.dtb
dtb-$(CONFIG_ARCH_K3) += myd-y62x-6252.dtb
dtb-$(CONFIG_ARCH_K3) += myd-y62x-6231.dtb
dtb-$(CONFIG_ARCH_K3) += myd-y62x-hdmi-audio.dtb
dtb-$(CONFIG_ARCH_K3) += myd-am62x-lvds.dtb
dtb-$(CONFIG_ARCH_K3) += myd-am62x-lvds-dual.dtb
